//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyDondecomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeProducto
    {
        public int LikeProductoID { get; set; }
        public Nullable<bool> valor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> usuarioID { get; set; }
        public Nullable<int> productoID { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
