//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyDondecomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.LikeMenu = new HashSet<LikeMenu>();
            this.Menu_Producto = new HashSet<Menu_Producto>();
        }
    
        public int menuID { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> pestauranteID { get; set; }
    
        public virtual ICollection<LikeMenu> LikeMenu { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual ICollection<Menu_Producto> Menu_Producto { get; set; }
    }
}
