//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyDondecomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.LikeProducto = new HashSet<LikeProducto>();
            this.Menu_Producto = new HashSet<Menu_Producto>();
        }
    
        public int productoID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string IMAGEN { get; set; }
        public string categoria { get; set; }
    
        public virtual ICollection<LikeProducto> LikeProducto { get; set; }
        public virtual ICollection<Menu_Producto> Menu_Producto { get; set; }
    }
}
