//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyDondecomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
    
        public int restauranteID { get; set; }
        public string nombre { get; set; }
        public string lugar { get; set; }
        public string telefono { get; set; }
        public Nullable<int> usuarioID { get; set; }

        public virtual List<Menu> Menu { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
