insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Tina', 'Moore', 179240323, 'tmoore0', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Amanda', 'Wright', 759518023, 'awright1', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Norma', 'Watson', 229111308, 'nwatson2', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Robert', 'Cruz', 832971942, 'rcruz3', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Adam', 'Fox', 882603189, 'afox4', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Rachel', 'Morales', 468641806, 'rmorales5', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Justin', 'Kelly', 859497041, 'jkelly6', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Rachel', 'Harvey', 537412571, 'rharvey7', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Carol', 'Ruiz', 462200218, 'cruiz8', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Betty', 'Harris', 887475516, 'bharris9', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jeremy', 'Lawson', 262054172, 'jlawsona', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Anne', 'Mitchell', 701963364, 'amitchellb', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Christine', 'Torres', 657780763, 'ctorresc', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jessica', 'Little', 301139381, 'jlittled', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Diane', 'Watson', 375144900, 'dwatsone', '123', 'cliente');

insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Harold', 'Woods', 868704108, 'hwoods0', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Aaron', 'Price', 389725311, 'aprice1', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Howard', 'Watkins', 416965202, 'hwatkins2', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jason', 'Kennedy', 318130126, 'jkennedy3', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Terry', 'Welch', 255394286, 'twelch4', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Ruby', 'Green', 857320386, 'rgreen5', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Theresa', 'Chavez', 884160841, 'tchavez6', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Timothy', 'Boyd', 736544113, 'tboyd7', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Albert', 'Thomas', 477880887, 'athomas8', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Shirley', 'Mccoy', 807421431, 'smccoy9', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Albert', 'Holmes', 414086568, 'aholmesa', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Timothy', 'Martin', 909224276, 'tmartinb', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jason', 'Woods', 192391892, 'jwoodsc', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Juan', 'Alexander', 792950166, 'jalexanderd', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Donna', 'Boyd', 392961562, 'dboyde', '123', 'administrador');

insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Voolia', 'Holy Cross', '63-(283)561-4860', 23);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Youopia', 'Farragut', '351-(561)937-9745', 24);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Fatz', 'Vermont', '359-(726)487-2686', 17);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Oyope', 'Boyd', '30-(993)452-1471', 29);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Dabfeed', 'Bay', '62-(533)461-0849', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Eimbee', 'Marquette', '370-(681)522-3470', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Roombo', 'Columbus', '86-(906)226-7822', 28);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Skipstorm', 'Westerfield', '351-(814)856-9664', 28);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Yoveo', 'Delladonna', '1-(901)167-4078', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Jaxworks', 'Rieder', '27-(728)739-6532', 23);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Yakidoo', 'Meadow Valley', '351-(368)208-5241', 25);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Quatz', 'Pennsylvania', '92-(843)988-4142', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Meemm', 'Linden', '86-(821)365-8650', 24);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Avaveo', 'Havey', '86-(858)531-3952', 27);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Latz', 'Spohn', '57-(155)984-2207', 30);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Kwilith', 'Steensland', '57-(757)436-7813', 19);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Jaloo', 'Farragut', '92-(910)836-7922', 27);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Wikibox', 'Morrow', '7-(325)917-4405', 18);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Camimbo', 'Jenna', '7-(549)356-8765', 18);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Edgewire', 'Everett', '256-(977)825-3040', 27);


insert into Menu (nombre, fecha, precio, pestauranteID) values ('clickbank.net', 2015-05-29, '8.23', 12);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('ning.com', 2015-06-16, '3.69', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('live.com', 2015-11-23, '9.89', 18);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('surveymonkey.com', 2015-06-30, '7.40', 8);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('cdc.gov', 2015-02-26, '3.75', 14);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('nba.com', 2015-11-07, '0.72', 11);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('shutterfly.com', 2015-05-19, '1.70', 20);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('live.com', 2015-10-06, '7.67', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('youku.com', 2015-10-02, '8.14', 9);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('mac.com', 2015-05-08, '0.32', 5);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('eventbrite.com', 2015-01-21, '3.16', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('phoca.cz', 2015-06-28, '4.80', 7);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('bizjournals.com', 2015-08-02, '3.31', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('msu.edu', 2015-11-30, '5.48', 12);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('unc.edu', 2014-12-16, '3.05', 14);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('tamu.edu', 2015-05-11, '6.67', 3);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('weather.com', 2015-01-06, '6.01', 19);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('msn.com', 2015-03-04, '5.85', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('youtube.com', 2015-04-11, '5.67', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('shareasale.com', 2015-11-22, '5.56', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('uiuc.edu', 2015-11-29, '6.47', 2);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('domainmarket.com', 2015-07-10, '8.10', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('is.gd', 2015-02-18, '7.87', 17);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('chronoengine.com', 2015-06-06, '1.92', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('google.it', 2015-04-19, '6.98', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('sina.com.cn', 2015-04-17, '5.99', 4);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('cnbc.com', 2015-01-30, '9.84', 5);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('edublogs.org', 2015-06-16, '3.50', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('about.me', 2014-12-13, '9.73', 4);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('netlog.com', 2015-11-15, '8.85', 9);

insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Jabberstorm', 'Paula', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'pgraham0@etsy.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Gigazoom', 'Amy', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'ahenderson1@theglobeandmail.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Katz', 'Tina', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'towens2@ted.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Tagtune', 'Ashley', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'amills3@bigcartel.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Youopia', 'Gloria', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'gfranklin4@360.cn');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Centimia', 'Victor', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'vfernandez5@creativecommons.org');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Oba', 'Laura', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'lwebb6@about.me');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Rhynyx', 'Bonnie', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'bmorris7@youtu.be');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Vinte', 'Jessica', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jsimpson8@craigslist.org');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Skidoo', 'Jason', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jmedina9@businessweek.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Oyope', 'Martha', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'mowensa@purevolume.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Devshare', 'Lori', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'lfranklinb@studiopress.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Voonyx', 'Joseph', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jcoxc@guardian.co.uk');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Katz', 'Judith', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jreedd@arizona.edu');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Dynabox', 'Brenda', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'bcolee@nyu.edu');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Gabtune', 'Raymond', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'rfreemanf@kickstarter.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Tagopia', 'Charles', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'cwoodsg@devhub.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Meetz', 'Gerald', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'gpalmerh@quantcast.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Yabox', 'Louis', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'lmitchelli@omniture.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Livetube', 'Ralph', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'rhayesj@ftc.gov');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Dabtype', 'Frances', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'fpalmerk@rambler.ru');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Feedfish', 'Catherine', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'ctorresl@nbcnews.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Janyx', 'Kathy', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'kedwardsm@skyrock.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Photobug', 'Willie', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'wthompsonn@people.com.cn');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Flipbug', 'Richard', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'rhuntero@twitter.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Bubbletube', 'Nicholas', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'ntuckerp@plala.or.jp');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Meevee', 'Roger', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'revansq@statcounter.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Eazzy', 'Willie', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'wpetersr@google.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Dabjam', 'Christopher', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'chowells@si.edu');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Yotz', 'Stephanie', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'sgrahamt@123-reg.co.uk');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Trilith', 'Arthur', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'apowellu@multiply.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Skinte', 'Justin', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jbrooksv@seattletimes.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Dynava', 'Ronald', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'rblackw@odnoklassniki.ru');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Fivespan', 'Rebecca', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'redwardsx@yandex.ru');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Browsecat', 'Samuel', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'sdixony@skype.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Zoombox', 'Diane', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'dwatkinsz@thetimes.co.uk');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Dynabox', 'Joshua', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jramirez10@marriott.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Jaxspan', 'Juan', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jrice11@is.gd');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Skyvu', 'Justin', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jgriffin12@nhs.uk');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Oyondu', 'Henry', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'harmstrong13@deliciousdays.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Devbug', 'Brandon', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'bthomas14@macromedia.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Katz', 'Wayne', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'wrichards15@ifeng.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Linktype', 'Wayne', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'wporter16@umich.edu');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Kaymbo', 'Harry', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'hgray17@sciencedaily.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Jayo', 'Teresa', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'twood18@columbia.edu');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Zoomzone', 'Alan', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'alittle19@360.cn');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Aimbo', 'Jeffrey', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'jrussell1a@drupal.org');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Jetwire', 'Raymond', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'rgrant1b@blogs.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Gigaclub', 'Kathleen', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'kwilliams1c@devhub.com');
insert into Producto (nombre, descripcion, IMAGEN, categoria) values ('Geba', 'Alan', 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'agreen1d@opensource.org');

insert into Menu_Producto (menuID, productoID) values (9, 10);
insert into Menu_Producto (menuID, productoID) values (17, 49);
insert into Menu_Producto (menuID, productoID) values (2, 3);
insert into Menu_Producto (menuID, productoID) values (1, 32);
insert into Menu_Producto (menuID, productoID) values (28, 8);
insert into Menu_Producto (menuID, productoID) values (11, 42);
insert into Menu_Producto (menuID, productoID) values (5, 46);
insert into Menu_Producto (menuID, productoID) values (26, 51);
insert into Menu_Producto (menuID, productoID) values (9, 9);
insert into Menu_Producto (menuID, productoID) values (18, 58);
insert into Menu_Producto (menuID, productoID) values (24, 5);
insert into Menu_Producto (menuID, productoID) values (22, 16);
insert into Menu_Producto (menuID, productoID) values (7, 55);
insert into Menu_Producto (menuID, productoID) values (13, 17);
insert into Menu_Producto (menuID, productoID) values (22, 58);
insert into Menu_Producto (menuID, productoID) values (19, 33);
insert into Menu_Producto (menuID, productoID) values (30, 13);
insert into Menu_Producto (menuID, productoID) values (13, 3);
insert into Menu_Producto (menuID, productoID) values (3, 15);
insert into Menu_Producto (menuID, productoID) values (17, 63);
insert into Menu_Producto (menuID, productoID) values (9, 66);
insert into Menu_Producto (menuID, productoID) values (8, 58);
insert into Menu_Producto (menuID, productoID) values (16, 15);
insert into Menu_Producto (menuID, productoID) values (4, 47);
insert into Menu_Producto (menuID, productoID) values (14, 28);
insert into Menu_Producto (menuID, productoID) values (19, 19);
insert into Menu_Producto (menuID, productoID) values (23, 65);
insert into Menu_Producto (menuID, productoID) values (28, 53);
insert into Menu_Producto (menuID, productoID) values (26, 48);
insert into Menu_Producto (menuID, productoID) values (15, 43);
insert into Menu_Producto (menuID, productoID) values (6, 8);
insert into Menu_Producto (menuID, productoID) values (28, 19);
insert into Menu_Producto (menuID, productoID) values (6, 15);
insert into Menu_Producto (menuID, productoID) values (25, 23);
insert into Menu_Producto (menuID, productoID) values (7, 26);
insert into Menu_Producto (menuID, productoID) values (22, 2);
insert into Menu_Producto (menuID, productoID) values (16, 70);
insert into Menu_Producto (menuID, productoID) values (1, 25);
insert into Menu_Producto (menuID, productoID) values (12, 40);
insert into Menu_Producto (menuID, productoID) values (20, 43);
insert into Menu_Producto (menuID, productoID) values (11, 49);
insert into Menu_Producto (menuID, productoID) values (16, 67);
insert into Menu_Producto (menuID, productoID) values (24, 13);
insert into Menu_Producto (menuID, productoID) values (11, 10);
insert into Menu_Producto (menuID, productoID) values (29, 38);
insert into Menu_Producto (menuID, productoID) values (13, 58);
insert into Menu_Producto (menuID, productoID) values (23, 17);
insert into Menu_Producto (menuID, productoID) values (12, 8);
insert into Menu_Producto (menuID, productoID) values (1, 1);
insert into Menu_Producto (menuID, productoID) values (16, 56);