insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Tina', 'Moore', 179240323, 'tmoore0', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Amanda', 'Wright', 759518023, 'awright1', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Norma', 'Watson', 229111308, 'nwatson2', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Robert', 'Cruz', 832971942, 'rcruz3', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Adam', 'Fox', 882603189, 'afox4', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Rachel', 'Morales', 468641806, 'rmorales5', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Justin', 'Kelly', 859497041, 'jkelly6', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Rachel', 'Harvey', 537412571, 'rharvey7', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Carol', 'Ruiz', 462200218, 'cruiz8', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Betty', 'Harris', 887475516, 'bharris9', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jeremy', 'Lawson', 262054172, 'jlawsona', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Anne', 'Mitchell', 701963364, 'amitchellb', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Christine', 'Torres', 657780763, 'ctorresc', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jessica', 'Little', 301139381, 'jlittled', '123', 'cliente');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Diane', 'Watson', 375144900, 'dwatsone', '123', 'cliente');

insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Harold', 'Woods', 868704108, 'hwoods0', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Aaron', 'Price', 389725311, 'aprice1', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Howard', 'Watkins', 416965202, 'hwatkins2', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jason', 'Kennedy', 318130126, 'jkennedy3', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Terry', 'Welch', 255394286, 'twelch4', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Ruby', 'Green', 857320386, 'rgreen5', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Theresa', 'Chavez', 884160841, 'tchavez6', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Timothy', 'Boyd', 736544113, 'tboyd7', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Albert', 'Thomas', 477880887, 'athomas8', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Shirley', 'Mccoy', 807421431, 'smccoy9', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Albert', 'Holmes', 414086568, 'aholmesa', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Timothy', 'Martin', 909224276, 'tmartinb', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Jason', 'Woods', 192391892, 'jwoodsc', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Juan', 'Alexander', 792950166, 'jalexanderd', '123', 'administrador');
insert into Usuario (nombre, apellidos, celular, usuario, password, rol) values ('Donna', 'Boyd', 392961562, 'dboyde', '123', 'administrador');

insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Voolia', 'Holy Cross', '63-(283)561-4860', 23);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Youopia', 'Farragut', '351-(561)937-9745', 24);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Fatz', 'Vermont', '359-(726)487-2686', 17);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Oyope', 'Boyd', '30-(993)452-1471', 29);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Dabfeed', 'Bay', '62-(533)461-0849', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Eimbee', 'Marquette', '370-(681)522-3470', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Roombo', 'Columbus', '86-(906)226-7822', 28);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Skipstorm', 'Westerfield', '351-(814)856-9664', 28);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Yoveo', 'Delladonna', '1-(901)167-4078', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Jaxworks', 'Rieder', '27-(728)739-6532', 23);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Yakidoo', 'Meadow Valley', '351-(368)208-5241', 25);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Quatz', 'Pennsylvania', '92-(843)988-4142', 20);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Meemm', 'Linden', '86-(821)365-8650', 24);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Avaveo', 'Havey', '86-(858)531-3952', 27);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Latz', 'Spohn', '57-(155)984-2207', 30);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Kwilith', 'Steensland', '57-(757)436-7813', 19);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Jaloo', 'Farragut', '92-(910)836-7922', 27);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Wikibox', 'Morrow', '7-(325)917-4405', 18);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Camimbo', 'Jenna', '7-(549)356-8765', 18);
insert into Restaurante (nombre, lugar, telefono, usuarioID) values ('Edgewire', 'Everett', '256-(977)825-3040', 27);


insert into Menu (nombre, fecha, precio, pestauranteID) values ('clickbank.net', 2015-05-29, '8.23', 12);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('ning.com', 2015-06-16, '3.69', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('live.com', 2015-11-23, '9.89', 18);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('surveymonkey.com', 2015-06-30, '7.40', 8);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('cdc.gov', 2015-02-26, '3.75', 14);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('nba.com', 2015-11-07, '0.72', 11);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('shutterfly.com', 2015-05-19, '1.70', 20);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('live.com', 2015-10-06, '7.67', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('youku.com', 2015-10-02, '8.14', 9);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('mac.com', 2015-05-08, '0.32', 5);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('eventbrite.com', 2015-01-21, '3.16', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('phoca.cz', 2015-06-28, '4.80', 7);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('bizjournals.com', 2015-08-02, '3.31', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('msu.edu', 2015-11-30, '5.48', 12);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('unc.edu', 2014-12-16, '3.05', 14);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('tamu.edu', 2015-05-11, '6.67', 3);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('weather.com', 2015-01-06, '6.01', 19);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('msn.com', 2015-03-04, '5.85', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('youtube.com', 2015-04-11, '5.67', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('shareasale.com', 2015-11-22, '5.56', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('uiuc.edu', 2015-11-29, '6.47', 2);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('domainmarket.com', 2015-07-10, '8.10', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('is.gd', 2015-02-18, '7.87', 17);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('chronoengine.com', 2015-06-06, '1.92', 16);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('google.it', 2015-04-19, '6.98', 10);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('sina.com.cn', 2015-04-17, '5.99', 4);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('cnbc.com', 2015-01-30, '9.84', 5);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('edublogs.org', 2015-06-16, '3.50', 1);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('about.me', 2014-12-13, '9.73', 4);
insert into Menu (nombre, fecha, precio, pestauranteID) values ('netlog.com', 2015-11-15, '8.85', 9);

insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Quire', '123-reg.co.uk', '9.12', 13, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Allergy and Hay Fever Reliever');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Oloo', 'stumbleupon.com', '9.01', 17, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'REYATAZ');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Kwinu', 'miitbeian.gov.cn', '4.41', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Galantamine');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Plambee', 'icio.us', '4.19', 7, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Mirtazapine');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Gigaclub', 'so-net.ne.jp', '2.95', 14, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Loxapine');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Teklist', 'amazon.co.uk', '7.82', 19, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Diphenhydramine HCL');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Digitube', 'soup.io', '5.01', 4, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Proactiv');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Twimm', 'etsy.com', '3.35', 4, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'NU-DERM STARTER SET NORMAL-OILY');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Shufflester', 'unicef.org', '2.26', 18, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'ZOVIRAX');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Devbug', 'aboutads.info', '2.39', 17, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'SmartRx Natural Pain Relief Sleeve KNEE');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Tanoodle', 'example.com', '2.52', 8, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Eucalyptus');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Fatz', 'microsoft.com', '1.60', 16, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Cefuroxime Axetil');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Youspan', 'examiner.com', '1.65', 19, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'HASOL Intensive Scalp Tonic');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Meembee', 'ifeng.com', '1.23', 20, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Effient');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Miboo', 'earthlink.net', '4.86', 19, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Glyburide');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Quinu', 'nifty.com', '3.05', 16, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Testosterone Cypionate');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Voomm', 'friendfeed.com', '4.79', 9, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'nasal decongestant');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Riffpedia', 'tiny.cc', '6.75', 7, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Amantadine HCl');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Rhynyx', 'reference.com', '1.73', 10, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Lidocaine Hydrochloride');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Buzzshare', 'github.com', '1.20', 1, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Gatifloxacin');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Dablist', 'shutterfly.com', '6.48', 15, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Antiseptic Mouth rinse');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Voolith', 'java.com', '7.41', 2, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'MENOPAUSE SUPPORT');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Zoombox', 'istockphoto.com', '9.33', 1, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'health mart loratadine');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Blogtag', 'aol.com', '5.81', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Menopause');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Fadeo', 'drupal.org', '7.35', 20, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'VASOPRESSIN');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Wordtune', 'epa.gov', '2.68', 7, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Cargo Tinted Moisturizer SPF 20');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Thoughtbeat', 'tinypic.com', '8.73', 2, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Soma');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Kazio', 'yolasite.com', '0.74', 9, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'MONSELS SOLUTION');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Quinu', 'usa.gov', '6.80', 8, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Nevirapine');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Youopia', 'loc.gov', '0.00', 19, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'GUNA-RHINO NOSE SPRAY');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Linkbridge', 'google.it', '0.56', 20, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'JIANZE SURGICAL SCRUB BRUSH NAIL CLEANER');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Flipstorm', 'archive.org', '5.90', 2, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Losartan Potassium');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Fivebridge', 'mail.ru', '2.08', 17, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Neomycin and Polymyxin B Sulfates and Hydrocortisone');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Thoughtmix', 'google.co.jp', '9.95', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'SUPRAX');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Jatri', 'indiatimes.com', '2.09', 1, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Calcium Acetate');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Aibox', 'alexa.com', '5.39', 10, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Quetiapine fumarate');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Brainverse', 'photobucket.com', '6.10', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'CANDIDA ALBICANS');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Vinte', 'prnewswire.com', '2.99', 1, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'LEVETIRACETAM');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Shuffledrive', 'drupal.org', '2.60', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'G-12');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Meemm', 'china.com.cn', '8.48', 15, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Wheat Bunt');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Photobug', 'dyndns.org', '2.47', 13, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'FAST RELIEF ARTROSAMIN');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Browseblab', 'wsj.com', '1.58', 13, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Integra Plus');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Trudoo', 'illinois.edu', '7.48', 13, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Warfarin Sodium');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Centimia', 'google.ru', '5.04', 17, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Eve Lom Radiance Lift Foundation SPF 15');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Youopia', 'newsvine.com', '5.97', 2, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'cephalexin');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Babbleset', 'auda.org.au', '3.77', 11, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Captopril');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Zoozzy', 'ow.ly', '7.52', 1, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Weight Loss Solution');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Dabvine', 'jimdo.com', '1.16', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'LANOCREME HYDRATING');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Topicware', 'ucoz.com', '6.28', 16, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Infectiguard Hand Sanitizer');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Realblab', 'bbc.co.uk', '1.59', 10, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Clonidine Hydrochloride');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Avavee', 'cornell.edu', '0.56', 18, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Gabapentin');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Edgeblab', 'seesaa.net', '8.85', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Wheezing HP');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Youbridge', 'wix.com', '3.41', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'GENOTROPIN');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Tanoodle', 'amazonaws.com', '3.55', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'NUMOTIZINE');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Devify', 'opera.com', '9.02', 13, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Furosemide');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Shuffletag', 'hexun.com', '6.21', 12, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Adult Low Dose Aspirin');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Vipe', 'networksolutions.com', '3.82', 10, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Corn Smut');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Thoughtsphere', 'blogs.com', '7.34', 11, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Eimbee', 'cargocollective.com', '2.28', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Bumetanide');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Skyvu', 'blogspot.com', '0.14', 14, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Amlodipine Besylate');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Skiba', 'histats.com', '9.13', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'SanaTos');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Twitternation', 'google.cn', '7.35', 20, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'DR. RECKEWEG R1 Anginacid');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Trilith', 'tinypic.com', '8.86', 6, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Flurazepam');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Buzzdog', 'acquirethisname.com', '0.20', 19, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Escitalopram Oxalate');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Realcube', 'homestead.com', '3.07', 5, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Dr Sheffield Muscle Rub Cream');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Dabshots', 'themeforest.net', '6.47', 12, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Standardized Kentucky (June) Bluegrass Pollen');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Divanoodle', 'usnews.com', '5.73', 18, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Givenchy Fluid Foundation Airy-light Mat Radiance SPF 20 Tint 5');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Eayo', 'e-recht24.de', '1.67', 15, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'MIDODRINE HYDROCHLORIDE');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Feedmix', 'histats.com', '5.89', 17, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Carvedilol');
insert into Producto (nombre, descripcion, precio, stock, IMAGEN, categoria) values ('Quimba', 'shop-pro.jp', '0.36', 2, 'http://peruanosenusa.net/wp-content/gallery/nuestra-mesa/247d1328072357-lomo-saltado-receta-lomo_saltado.jpg', 'Bupropion Hydrochloride');


insert into Menu_Producto (menuID, productoID) values (9, 10);
insert into Menu_Producto (menuID, productoID) values (17, 49);
insert into Menu_Producto (menuID, productoID) values (2, 3);
insert into Menu_Producto (menuID, productoID) values (1, 32);
insert into Menu_Producto (menuID, productoID) values (28, 8);
insert into Menu_Producto (menuID, productoID) values (11, 42);
insert into Menu_Producto (menuID, productoID) values (5, 46);
insert into Menu_Producto (menuID, productoID) values (26, 51);
insert into Menu_Producto (menuID, productoID) values (9, 9);
insert into Menu_Producto (menuID, productoID) values (18, 58);
insert into Menu_Producto (menuID, productoID) values (24, 5);
insert into Menu_Producto (menuID, productoID) values (22, 16);
insert into Menu_Producto (menuID, productoID) values (7, 55);
insert into Menu_Producto (menuID, productoID) values (13, 17);
insert into Menu_Producto (menuID, productoID) values (22, 58);
insert into Menu_Producto (menuID, productoID) values (19, 33);
insert into Menu_Producto (menuID, productoID) values (30, 13);
insert into Menu_Producto (menuID, productoID) values (13, 3);
insert into Menu_Producto (menuID, productoID) values (3, 15);
insert into Menu_Producto (menuID, productoID) values (17, 63);
insert into Menu_Producto (menuID, productoID) values (9, 66);
insert into Menu_Producto (menuID, productoID) values (8, 58);
insert into Menu_Producto (menuID, productoID) values (16, 15);
insert into Menu_Producto (menuID, productoID) values (4, 47);
insert into Menu_Producto (menuID, productoID) values (14, 28);
insert into Menu_Producto (menuID, productoID) values (19, 19);
insert into Menu_Producto (menuID, productoID) values (23, 65);
insert into Menu_Producto (menuID, productoID) values (28, 53);
insert into Menu_Producto (menuID, productoID) values (26, 48);
insert into Menu_Producto (menuID, productoID) values (15, 43);
insert into Menu_Producto (menuID, productoID) values (6, 8);
insert into Menu_Producto (menuID, productoID) values (28, 19);
insert into Menu_Producto (menuID, productoID) values (6, 15);
insert into Menu_Producto (menuID, productoID) values (25, 23);
insert into Menu_Producto (menuID, productoID) values (7, 26);
insert into Menu_Producto (menuID, productoID) values (22, 2);
insert into Menu_Producto (menuID, productoID) values (16, 70);
insert into Menu_Producto (menuID, productoID) values (1, 25);
insert into Menu_Producto (menuID, productoID) values (12, 40);
insert into Menu_Producto (menuID, productoID) values (20, 43);
insert into Menu_Producto (menuID, productoID) values (11, 49);
insert into Menu_Producto (menuID, productoID) values (16, 67);
insert into Menu_Producto (menuID, productoID) values (24, 13);
insert into Menu_Producto (menuID, productoID) values (11, 10);
insert into Menu_Producto (menuID, productoID) values (29, 38);
insert into Menu_Producto (menuID, productoID) values (13, 58);
insert into Menu_Producto (menuID, productoID) values (23, 17);
insert into Menu_Producto (menuID, productoID) values (12, 8);
insert into Menu_Producto (menuID, productoID) values (1, 1);
insert into Menu_Producto (menuID, productoID) values (16, 56);