USE MASTER
go

DROP DATABASE dondeComer
go

CREATE DATABASE dondeComer
go

USE dondeComer;

CREATE TABLE Usuario(
usuarioID INT IDENTITY PRIMARY KEY NOT NULL,
nombre VARCHAR(50),
apellidos VARCHAR(50),
celular CHAR(9),
usuario VARCHAR(50),
password VARCHAR(50),
rol VARCHAR(50)
);

CREATE TABLE Restaurante(
restauranteID INT IDENTITY PRIMARY KEY NOT NULL,
nombre VARCHAR(50),
descripcion VARCHAR(50),
lugar VARCHAR(50),
telefono VARCHAR(50),
latitud VARCHAR(50),
longitud VARCHAR(50),
usuarioID INT FOREIGN KEY REFERENCES Usuario
);

CREATE TABLE Producto(
productoID INT IDENTITY PRIMARY KEY NOT NULL,
nombre VARCHAR(50),
descripcion TEXT,
imagen TEXT,
categoria VARCHAR(50)
);

CREATE TABLE Menu(
menuID INT IDENTITY PRIMARY KEY NOT NULL,
nombre VARCHAR(50),
fecha DATE,
precio MONEY,
restauranteID INT FOREIGN KEY REFERENCES Restaurante
);

CREATE TABLE Menu_Producto(
MenuProductoID INT IDENTITY PRIMARY KEY,
menuID INT FOREIGN KEY REFERENCES Menu NOT NULL,
productoID INT FOREIGN KEY REFERENCES Producto NOT NULL
);

CREATE TABLE LikeProducto(
LikeProductoID INT IDENTITY PRIMARY KEY NOT NULL,
valor BIT,
fecha DATE,
usuarioID INT FOREIGN KEY REFERENCES Usuario,
productoID INT FOREIGN KEY REFERENCES Producto
);